// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjdRJ-KXE0XCHVKbpG51C_IsmiDhm4Pqs',
    appId: '1:744855907134:web:5bc81fc8bbd359882a5a6f',
    messagingSenderId: '744855907134',
    projectId: 'flutter-first-project-d0d5b',
    authDomain: 'flutter-first-project-d0d5b.firebaseapp.com',
    databaseURL: 'https://flutter-first-project-d0d5b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-first-project-d0d5b.appspot.com',
    measurementId: 'G-52E943NS81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFFAXHcEoy0chpTYbDDdP6e9VZtG5tXqQ',
    appId: '1:744855907134:android:70beefb5f4b07ace2a5a6f',
    messagingSenderId: '744855907134',
    projectId: 'flutter-first-project-d0d5b',
    databaseURL: 'https://flutter-first-project-d0d5b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-first-project-d0d5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2M3puZxPvImi6LK0Fy_D5AIM2roH9sEY',
    appId: '1:744855907134:ios:e892573042e049fc2a5a6f',
    messagingSenderId: '744855907134',
    projectId: 'flutter-first-project-d0d5b',
    databaseURL: 'https://flutter-first-project-d0d5b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-first-project-d0d5b.appspot.com',
    iosBundleId: 'com.example.managejob',
  );

}